/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CategoryImport } from './routes/$category'
import { Route as ProductProductIdImport } from './routes/product/$productId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CategoryRoute = CategoryImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProductProductIdRoute = ProductProductIdImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryImport
      parentRoute: typeof rootRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$category': typeof CategoryRoute
  '/product/$productId': typeof ProductProductIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$category': typeof CategoryRoute
  '/product/$productId': typeof ProductProductIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$category': typeof CategoryRoute
  '/product/$productId': typeof ProductProductIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$category' | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$category' | '/product/$productId'
  id: '__root__' | '/' | '/$category' | '/product/$productId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CategoryRoute: typeof CategoryRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CategoryRoute: CategoryRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$category",
        "/product/$productId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$category": {
      "filePath": "$category.tsx"
    },
    "/product/$productId": {
      "filePath": "product/$productId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
